"""Float64 reference of the EDT bilinear sampler: samples the track blob and writes fixtures_edt.h."""
import struct
import sys
from pathlib import Path

import numpy as np

from sim.track import blob_path

HERE = Path(__file__).resolve().parent
MAP = "lab-20260705"
BLOB = blob_path(MAP)
OUT = HERE / "fixtures_edt.h"
BLOB_C_PATH = f"../tracks/{MAP}/{MAP}.blob"

HEADER_FMT = "<2I 2i f 2f i 2i"  # magic, version, W, H, res, ox, oy, n, edt_off, rline_off
MAGIC = struct.unpack("<I", b"RRBC")[0]

# Match the C grid step exactly: floor + the (ix+1>=W || iy+1>=H) bounds rule.
SWEEP_STEP = 3          # sample every 3rd cell in each axis (~3.4k pts)
SWEEP_OFF = (0.37, 0.61)  # fractional offset -> forces a non-trivial bilinear blend


def load_blob(path: Path):
    raw = path.read_bytes()
    fields = struct.unpack_from(HEADER_FMT, raw, 0)
    magic, version, W, H, res, ox, oy, n_rline, edt_off, rline_off = fields
    if magic != MAGIC:
        sys.exit(f"bad magic in {path}: {magic:#x} != {MAGIC:#x}")
    edt = np.frombuffer(raw, dtype="<f4", count=H * W, offset=edt_off).reshape(H, W)
    rline = np.frombuffer(raw, dtype="<f4", count=n_rline * 10,
                          offset=rline_off).reshape(n_rline, 10)
    return dict(version=version, W=W, H=H, res=res, ox=ox, oy=oy,
                n_rline=n_rline, edt=edt, rline=rline)


def py_bilinear(b, wx, wy):
    """Exact mirror of bilinear_sample_edt() in roboracer.h."""
    W, H, res, ox, oy, edt = b["W"], b["H"], b["res"], b["ox"], b["oy"], b["edt"]
    gx = (wx - ox) / res
    gy = (wy - oy) / res
    ix = int(np.floor(gx))
    iy = int(np.floor(gy))
    a = gx - ix
    bb = gy - iy
    if ix < 0 or iy < 0 or ix + 1 >= W or iy + 1 >= H:
        return -1.0
    q11 = edt[iy, ix]
    q21 = edt[iy, ix + 1]
    q12 = edt[iy + 1, ix]
    q22 = edt[iy + 1, ix + 1]
    r1 = q11 * (1 - a) + q21 * a
    r2 = q12 * (1 - a) + q22 * a
    return float(r1 * (1 - bb) + r2 * bb)


def build_points(b):
    """Return list of (wx, wy, expected, on_track)."""
    pts = []

    # 1. ON-TRACK: raceline world coords
    for x, y in b["rline"][:, :2]:
        pts.append((float(x), float(y), py_bilinear(b, x, y), 1))

    # 2. SWEEP: fractional-offset grid over the interior
    W, H, res, ox, oy = b["W"], b["H"], b["res"], b["ox"], b["oy"]
    fx, fy = SWEEP_OFF
    for col in range(0, W - 1, SWEEP_STEP):
        for row in range(0, H - 1, SWEEP_STEP):
            wx = ox + (col + fx) * res
            wy = oy + (row + fy) * res
            pts.append((wx, wy, py_bilinear(b, wx, wy), 0))

    # 3. OFFMAP: just outside each edge + far away -> sentinel -1.0
    for wx, wy in [
        (ox - res, oy + res),                 # left of grid
        (ox + res, oy - res),                 # below grid
        (ox + (W + 1) * res, oy + res),       # right of grid
        (ox + res, oy + (H + 1) * res),       # above grid
        (ox + (W - 0.5) * res, oy + res),     # last column (ix+1>=W truncation)
        (1e6, 1e6),                           # far away
    ]:
        pts.append((wx, wy, py_bilinear(b, wx, wy), 0))

    return pts


def cf(x):
    """Format a float as a valid C float literal (always has '.' or 'e' before 'f')."""
    s = f"{x:.8g}"
    if "." not in s and "e" not in s and "E" not in s and "inf" not in s and "nan" not in s:
        s += ".0"
    return s + "f"


def emit(b, pts):
    n_on = sum(p[3] for p in pts)
    with open(OUT, "w") as f:
        f.write("/* AUTO-GENERATED by reference_edt.py -- do not edit. */\n")
        f.write("#ifndef FIXTURES_EDT_H\n#define FIXTURES_EDT_H\n\n")
        f.write(f'#define EDT_BLOB_PATH "{BLOB_C_PATH}"\n\n')
        f.write("/* header values the C loader must reproduce */\n")
        f.write(f"#define EDT_VERSION  {b['version']}\n")
        f.write(f"#define EDT_W        {b['W']}\n")
        f.write(f"#define EDT_H        {b['H']}\n")
        f.write(f"#define EDT_RES      {cf(b['res'])}\n")
        f.write(f"#define EDT_OX       {cf(b['ox'])}\n")
        f.write(f"#define EDT_OY       {cf(b['oy'])}\n")
        f.write(f"#define EDT_N_RLINE  {b['n_rline']}\n\n")
        f.write("typedef struct { float wx, wy, expected; int on_track; } EdtCase;\n")
        f.write(f"#define N_EDT_CASES {len(pts)}\n")
        f.write(f"#define N_EDT_ONTRACK {n_on}\n")
        f.write("static const EdtCase EDT_CASES[N_EDT_CASES] = {\n")
        for wx, wy, exp, on in pts:
            f.write(f"  {{{cf(wx)}, {cf(wy)}, {cf(exp)}, {on}}},\n")
        f.write("};\n\n#endif\n")
    print(f"wrote {OUT.name}: {len(pts)} cases ({n_on} on-track, "
          f"{len(pts) - n_on} sweep/offmap)")
    # quick sanity in Python too: every on-track point should be positive clearance
    bad = [(p[0], p[1], p[2]) for p in pts if p[3] == 1 and p[2] <= 0]
    if bad:
        print(f"  WARNING: {len(bad)} raceline points read <=0 clearance "
              f"(first: {bad[0]}) -- transform/flip likely wrong!")
    else:
        print(f"  all {n_on} raceline points have positive clearance "
              f"(min={min(p[2] for p in pts if p[3]==1):.3f} m)")


def main():
    if not BLOB.exists():
        sys.exit(f"blob not found: {BLOB}")
    b = load_blob(BLOB)
    pts = build_points(b)
    emit(b, pts)


if __name__ == "__main__":
    main()
